const ARG_REGISTER_DRIVER = 'register_driver'
const ARG_DISPATCH_DRIVER = 'dispatch_driver_for_a_booking'
 const ARG_COMPLETE_BOOKING = 'complete_booking'
 const ARG_DRIVERS_COMPLETED_BOOKING_GT = 'drivers_completed_booking_gt'
 const ARG_DRIVERS_COMPLETED_DISTANCE_GT_10 = 'booking_completed_distance_gt_10'

 const DRIVER_STATUS_AVAILABLE = 'AVAILABLE'
 const DRIVER_STATUS_BOOKED = 'BOOKED'

 const BOOKING_STATUS_ONGOING = 'ONGOING'
 const BOOKING_STATUS_COMPLETED = 'COMPLETED' 


module.exports = {
    ARG_COMPLETE_BOOKING,
    ARG_DISPATCH_DRIVER,
    ARG_DRIVERS_COMPLETED_BOOKING_GT,
    ARG_DRIVERS_COMPLETED_DISTANCE_GT_10,
    ARG_REGISTER_DRIVER,
    DRIVER_STATUS_AVAILABLE,
    DRIVER_STATUS_BOOKED,
    BOOKING_STATUS_COMPLETED,
    BOOKING_STATUS_ONGOING
}